### ISSUE TITLE
Evitar limpiar las cabeceras en cada Scenario

### ISSUE THREAD

**Issue by rommelayala** [veepee-oss/gingerspec#54]
Estaria bien evitar usar este STEP <Given I clear headers from previous request> ya que los scenarios no se ven limpios

Scenario: Get data from som API
    Given I securely send requests to 'Some.APIUrl'
    When I send a 'GET' request to '/users/123'
    Then the service response status must be '200'

Scenario: Get data from another endponit
    **Given I clear headers from previous request**
    And I securely send requests to 'Another.APIUrl'
    And I set headers:
      | Authorization | !{token} |
    When I send a 'GET' request to '/employee/detail/654'

**Comment by josefd8** [comment]
Hey @rommelayala 

If you're using the @rest annotation for the Scenario (or in the feature), **Gingerspec will automatically close the REST client when the scenario finishes** and will start a new "fresh" instance for the next Scenario. 

So, there is no need to execute "Given I clear headers from previous request" at the beginning of a scenario, since _for this scenario_ there is not a previous request, is a "fresh" instance. **Headers/cookies/responses are not inherited between scenarios**. The scenario is the smallest test unit and is independent of other scenarios in the same feature.

Could you confirm if headers/cookies/responses are not really being cleaned for each scenario? if this is the case, it may be a bug

**Comment by josefd8** [comment]
- The steps to clear previous headers/cookies and URL parameters were removed. Now, a new rest client is initialized as soon as a request completes its execution. This new rest client will have the same base URI and port as the one set previously in the scenario (with the step _Given I send requests to '<URL>:<PORT>'_) but without headers/cookies/url parameters. 
- Fixed a long-standing issue with logging. Now, using -DlogLevel=DEBUG will print all information of the request and response
